security:
  basic:
    enabled: false
zuul:
  routes:
    exampleAppServer:
      path: /oasp4j-sample-server/**
      url: http://openam.sixgems.org:8081/oasp4j-sample-server
auth:
  sessionAttributeName: jwtSessionToken
openam:
  ssotoken:
    properties:
      username: UserId
    attributes:
      groupsAttribute: objectClass
      additionalAttributes: mail,employeeNumber,postalAddress
