security:
  basic:
    enabled: false
zuul:
  routes:
    logout:
      path: /logout
      url: http://openam.sixgems.org:8080/OpenAMTest/UI/Logout
    exampleAppServer:
      path: /oasp4j-sample-server/**
      url: http://openam.sixgems.org:8081/oasp4j-sample-server
auth:
  sessionAttributeName: jwtSessionToken
openam:
  ssotoken:
    properties:
      username: UserId
    attributes:
      additionalAttributes: cn,mail,employeeNumber,postalAddress
